### ISSUE TITLE
Integration doesn't work with @astro-js/mdx

### ISSUE THREAD

**Issue by kotosha-real** [MatthiesenXYZ/astro-gists#14]
Hello!

**Describe the bug**
Integration doesn't work with `@astro-js/mdx`. Both `build` and `dev` scripts throw this error:

```
Incorrect integration order: To allow code blocks on MDX pages to use astro-expressive-code, please move astroExpressiveCode() before mdx() in the "integrations" array of your Astro config file.
  Stack trace:
    at astro:config:setup (file:///workspaces/workspace/node_modules/.pnpm/astro-expressive-code@0.33.4_astro@4.4.5/node_modules/astro-expressive-code/dist/index.js:196:17)
    at async sync (file:///workspaces/workspace/node_modules/.pnpm/astro@4.4.5_typescript@5.3.3/node_modules/astro/dist/core/sync/index.js:27:20)
    at async runCommand (file:///workspaces/workspace/node_modules/.pnpm/astro@4.4.5_typescript@5.3.3/node_modules/astro/dist/cli/index.js:149:27)
```

**To Reproduce**
Repro is [here](https://codesandbox.io/p/devbox/exciting-raman-mypyk2). Just run `pnpm build` or `pnpm dev` in terminal.

**Expected behavior**
`@astro-js/mdx` and `astro-gists` integrations don't clash.

**Additional context**
I needed to add a gist to my blog, so I wrote my own package first and then got to yours. It might be of some interest, [here it is](https://github.com/kotosha-real/astro-gist).

**Comment by Adammatthiesen** [comment]
This error is due to my version of expressive-code being included before after MDX is loaded in the integration list... For expressive code to work with mdx you have to load my integration Then MDX

```mjs
import { defineConfig } from "astro/config";
import astroGist from "@matthiesenxyz/astro-gists";
import mdx from "@astrojs/mdx";

// https://astro.build/config
export default defineConfig({
  integrations: [astroGist(), mdx()]
});
```

**Comment by kotosha-real** [comment]
Yeah, I get it, but here's what happens:

<img width="500" alt="image" src="https://github.com/MatthiesenXYZ/astro-gists/assets/51344103/565ed9f3-7145-442c-8d21-c9384e01bd80">

Your integration is before `mdx`, but I still got an error.

**Comment by Adammatthiesen** [comment]
Okay, I released a new version v0.1.0 that now includes mdx as the mdx integration is just a pain in the rear-end 99% of the time when working with expressiveCode, and since I'm not shipping a standard version of expressiveCode it seems to be having an issue and just forcing my version to be at the end of the integration array even when the actual integration is located in the front.

This update should resolve the MDX issue

**Comment by kotosha-real** [comment]
Checked it, `mdx` pages crash. With explicit `@astro/mdx` integration everything works fine. Updated [repro](https://codesandbox.io/p/devbox/exciting-raman-mypyk2), here's the link to `mdx` page — https://mypyk2-4321.csb.app/mdx

`astro.config.mjs` is as follows:

```
import { defineConfig } from "astro/config";
import mdx from "@astrojs/mdx";

import astroGists from "@matthiesenxyz/astro-gists";

// https://astro.build/config
export default defineConfig({
  integrations: [astroGists({ MDXIntegration: true })],
});

```

**Comment by Adammatthiesen** [comment]
Please remove the MDX integration from your local project to prevent conflicts... also in order for me to use the sandbox you have to grant permissions to outside users.  it still wont let me view it

**Comment by kotosha-real** [comment]
It wasn't listed, don't mind the `import` in the code above, it wasn't used. Here's the [shareable link](https://codesandbox.io/p/devbox/exciting-raman-mypyk2?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clt7ousee00083u6kri8d37qe%2522%252C%2522sizes%2522%253A%255B67.44976816074188%252C32.55023183925812%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clt7ousee00023u6kzh4kt3nj%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clt7ousee00063u6kon5lgxvr%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clt7ousee00073u6kr4z9neih%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clt7ousee00023u6kzh4kt3nj%2522%253A%257B%2522id%2522%253A%2522clt7ousee00023u6kzh4kt3nj%2522%252C%2522tabs%2522%253A%255B%255D%257D%252C%2522clt7ousee00073u6kr4z9neih%2522%253A%257B%2522id%2522%253A%2522clt7ousee00073u6kr4z9neih%2522%252C%2522activeTabId%2522%253A%2522clt8u457700px3u6kyy46ha5r%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4321%252C%2522id%2522%253A%2522clt8u457700px3u6kyy46ha5r%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%2522%257D%255D%257D%252C%2522clt7ousee00063u6kon5lgxvr%2522%253A%257B%2522id%2522%253A%2522clt7ousee00063u6kon5lgxvr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clt7ousee00053u6ksxxe22ni%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clt5g9zxv0036dhhi9na2aikw%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clt7ousee00053u6ksxxe22ni%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) to the repro. Didn't think it would be private, rookie mistake :D

**Comment by Adammatthiesen** [comment]
MDX should now be fixed as of [v0.1.1](https://github.com/MatthiesenXYZ/astro-gists/releases/tag/%40matthiesenxyz%2Fastro-gists%400.1.1)

**Comment by kotosha-real** [comment]
Yes, it did the trick. Thanks!

**Comment by Adammatthiesen** [comment]
Closing the issue now that MDX is working.  

Note for the Future:  After talking with the Maintainer of ExpressiveCode he will be working to solve the integration order issue (as that is now something he can handle within his integration itself) to be able to prevent future issues and one that fix is implemented,  MDX will be removed back as a separate package at that time and of course will be noted in the changelog once it is fixed.
