### ISSUE TITLE
Exceeding the octokit quota results in a broken page

### ISSUE THREAD

**Issue by kotosha-real** [MatthiesenXYZ/astro-gists#15]
**Describe the bug**
Exceeding the octokit quota will result in pages containing gists getting stuck while loading. The worst part is that the quota is really low, so it takes almost no effort to exceed it.

**To Reproduce**
Repro is [here](https://codesandbox.io/p/devbox/exciting-raman-mypyk2).

1. Remove `mdx()` integration so the project could start;
2. Start dev mode from the terminal;
3. Open the preview in a different tab (it tends to show "Too much redirect" error);
4. Refresh the page about 10 times;
5. Notice `Request quota exhausted for request GET /gists/{gist_id}` log in the terminal. The page also won't load.

I've also tried checking the preview mode, but I can't build the project:

```
07:05:03 [build] Building static entrypoints...
07:05:08 [ERROR] [vite] x Build failed in 5.26s
[vite]: Rollup failed to resolve import "fsevents" from "/workspaces/workspace/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
  Stack trace:
    at viteWarn (file:///workspaces/workspace/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:67078:27)
    at onwarn (file:///workspaces/workspace/node_modules/.pnpm/vite@5.1.4/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:66810:13)
    at Object.logger [as onLog] (file:///workspaces/workspace/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:19965:9)
    at ModuleLoader.resolveDynamicImport (file:///workspaces/workspace/node_modules/.pnpm/rollup@4.12.0/node_modules/rollup/dist/es/shared/node-entry.js:18967:58)
```

The project itself is the [Astro codesandbox official template](https://codesandbox.io/s/astro-j1qiqf) fork with two integrations installed with `astro add`.

**Expected behavior**
I suppose this behavior is expected, but it also makes the package almost impossible to use. You'll never know when the quota will be exceeded, and when it is, pages containing gists will simply break.

Edit: I also noticed that in repro everything works without GitHub personal token.

**Comment by Adammatthiesen** [comment]
I was unable to click into your reproduction... But I only encountered this error when i did not have a token assigned.  Octokit does allow you to use it without a token but it is HEAVILY limited.  The only solution for me to solve it was by adding the setup for the access token.  I have a empty token that i was using for DEV that i was able to refresh 100s of times without facing any errors... so this is really weird and i'd love a chance to investigate!

**Comment by kotosha-real** [comment]
I'm pretty sure I tried both with and without the secret. I'll give it another try tomorrow and get back with results.

**Comment by Adammatthiesen** [comment]
Just in case its something to do with the code sandbox, I've also implemented some better logs to verify that it can see your .env defined token.  As well as just trying to keep my own sanity and verify things are working the way they should 😄

**Comment by Adammatthiesen** [comment]
Also just to clarify according to GitHub:

[Primary rate limit for unauthenticated users](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-unauthenticated-users)
You can make unauthenticated requests if you are only fetching public data. Unauthenticated requests are associated with the originating IP address, not with the user or application that made the request.

The primary rate limit for unauthenticated requests is 60 requests per hour.

[Primary rate limit for authenticated users](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28#primary-rate-limit-for-authenticated-users)
You can use a personal access token to make API requests. Additionally, you can authorize a GitHub App or OAuth app, which can then make API requests on your behalf.

All of these requests count towards your personal rate limit of 5,000 requests per hour. Requests made on your behalf by a GitHub App that is owned by a GitHub Enterprise Cloud organization have a higher rate limit of 15,000 requests per hour. Similarly, requests made on your behalf by a OAuth app that is owned or approved by a GitHub Enterprise Cloud organization have a higher rate limit of 15,000 requests per hour if you are a member of the GitHub Enterprise Cloud organization.

So if the Token is properly present, there should be no reason that Octokit should throttle... since it just uses the RestAPI

**Comment by kotosha-real** [comment]
Seems like you're right. But if there's a quota, then there's a possibility of it being exceeded. I think some explicit logs and rendering the link to the gist when this happens will be a good solution here.

**Comment by Adammatthiesen** [comment]
#18 will include those logs.  

But again... If your using a token (Like explicitly mentioned in the Readme and if you don't have it the console will yell now as well) you should not be facing any issues with request limits in the first place as the request limit is quite high.  and there are available options from github to raise said limit as well.

**Comment by kotosha-real** [comment]
You're right, but any external quota, no matter how high, is the potential breaking point. Let's say you have 15000 requests per hour. Suppose you have a blog with 10 articles, each with 10 gists. You have 15000 / (10 * 10) = 150 page views per hour until the quota is exceeded. It's a rough approximation, but the seemingly high limit can shrink very quickly, and there's no way to raise it any higher (if there is, fine, but you should be somehow aware that you are almost there). Also, you can never rule out a DDoS, which will drain 15000 requests in a couple of minutes, and the remaining time of an hour everything sill be broken.

That's why I suggested having a fallback with a link to the gist, because that way the component will fail gracefully and the user will still get the information they want, just in a different view.

**Comment by Adammatthiesen** [comment]
Just saw your code sandbox, and noticed the `.env` file is supposed to be at the root of the project, not within the `/src` directory.  That would be why your hitting the rate limit so quickly. It is not seeing your token at all.

Page views per hour would only be applicable with Astro in SSR mode, in SSG mode the HTML is directly rendered and NOT using API requests every single poll of the webpage.  So if you are building a SSG(Static, the default for Astro) website the only time Octokit would be called is during build time.  Now for SSR I could see this as a problem.  And there are plans on my notepad to include such fixes for that type of situation.  BUT in general most `Astro` users will not face this issue as most Astro projects are statically built.

**Comment by kotosha-real** [comment]
Sandbox didn't allow me to save `.env` at all so I checked it locally. It worked as expected, no issue here.

Point about SSG is valid. Some info about potential problems in SSR mode in the package `README.md` would be useful though.

**Comment by Adammatthiesen** [comment]
This issue is now complete, as of #24
